spring:
  application:
    name: file-policy
  profiles:
    default: dev

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        jdbc.time_zone: UTC

  flyway:
    enabled: true

  thymeleaf:
    cache: false

management:
  endpoints:
    web:
      exposure:
        include: health,info

server:
  port: 8080
