server:
  port: ${PORT:8080}

spring:
  datasource:
    url: jdbc:${MYSQL_PUBLIC_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

  flyway:
    enabled: true
    locations: classpath:db/migration
