server:
  port: ${PORT:8080}

spring:
  datasource:
    url: jdbc:mysql://${MYSQLHOST:${DB_HOST}}:${MYSQLPORT:${DB_PORT:3306}}/${MYSQLDATABASE:${DB_NAME:filepolicy}}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=utf8mb4
    username: ${MYSQLUSER:${DB_USERNAME}}
    password: ${MYSQLPASSWORD:${DB_PASSWORD}}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

  flyway:
    enabled: true
    locations: classpath:db/migration
